language: c

# Request Ubuntu Trusty (14.04 LTS).
dist: trusty

sudo: required

branches:
  only:
    - master
    # Test all issue* branches. Saves you opening a PR.
    - /^issue.*/

git:
  submodules: false

env:
  - GHC_VER=8.6.5
  - GHC_VER=8.4.4
  - GHC_VER=8.2.2
  - GHC_VER=8.0.2

cache:
  directories:
    - $HOME/.stack

before_install:
  - sudo -E apt-add-repository -y "ppa:hvr/ghc"
  - travis_apt_get_update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install ghc-${GHC_VER}

  - export PATH=/opt/ghc/$GHC_VER/bin:$PATH
  - mkdir -p ~/.local/bin && export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 |
    tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  - export ARGS="--stack-yaml stack-${GHC_VER}.yaml --no-terminal --system-ghc"

  - echo "*** GHC version ***"     && ghc     --version &&
    echo "*** Stack version ***"   && stack   --version

install:
  - stack build ${ARGS} --only-dependencies

script:
  - travis_wait 35 stack build ${ARGS}
  - stack exec ${ARGS} -- fix-agda-whitespace --check
