language: c
dist: trusty
sudo: required
branches:
  only:
  - master
  - "/^issue.*/"
  - "/^release-.*/"
git:
  submodules: false

env:
  global:
  - BIN=fix-whitespace
  matrix:
  - GHC_VER=8.6.5

cache:
  directories:
  - "$HOME/.stack"

before_install:
- sudo -E apt-add-repository -y "ppa:hvr/ghc"
- travis_apt_get_update
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install ghc-${GHC_VER}
- export PATH=/opt/ghc/$GHC_VER/bin:$PATH
- mkdir -p ~/.local/bin && export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- export ARGS="--stack-yaml stack-${GHC_VER}.yaml --no-terminal --system-ghc"
- echo "*** GHC version ***"     && ghc     --version && echo "*** Stack version ***"   &&
  stack   --version

install:
- stack build ${ARGS} --only-dependencies
- stack build ${ARGS}

script:
- stack exec ${ARGS} -- ${BIN} --check

before_deploy:
- rm *.lock
- stack install ${ARGS} --local-bin-path .
- strip ${BIN}
- gzip ${BIN}

deploy:
  provider: releases
  skip_cleanup: true
  file: "${BIN}.gz"
  all_branches: true
  on:
    repo: agda/fix-whitespace
    condition: $GHC_VER = 8.6.5
    tags: true
  api_key:
    secure: Ku4XueVQfX2Ie/9YFRwV2A5xaXCHSG18mRnZcmlIYf0AhXpdJIwYBDLf/ZN5gEAQktWlpWoyJIoRifLMTp3rCMkx4FrThm3X+qpXeP3SBet3skH50/6ve3DkhFNOzCKHpuiiPY95m1zkz0Pd4/Giv/EJZSz5ASXSph/ctQUHdFdNOuCXzjHJ9siOnZp6j8/KxNJKkt6YC5dt15N6KiPqMefUJjuT9F6QJplZYG6GbqSqIXdSeirJabI4ebH9xEwNHIIStnBwrtwx4uAbg3ossCl/Bu5c9PiTkIH80DW4lGOeOHtwtEEad98qL+IMsiIRH6C31EuMZlCPJedDzYF1hdH9cNiYSo+JFM5T14DSoxMMw4qDk98TBBOXex6MB/t2eHnOeQ6Vb5Y9HYNxkEN+ehZ3geaMmk8RYJ16lnDZwwY4wqDCUCcbNmnzz0p/rlSnL40Zpent5WKznhp5EPmldZB5RHE9RRvg+dsWWpQ4qErIN+NPS/GXNk3cARjoVRXQIgI4D8BlCwShPiNK35ybHEqZIYUlcK4KH8sOlBf9nTxSm9hio9I2xu4ADe3B++ShYwkza9jpMAo/AFf76hPCOJBsjqQYPBULhFlVtgfDgiBVNHpbbFDCFs/SPtgUwY79wDdWkeJwNG/94ck/eYK3DSvwh3Yg6p8hG7d9eQby3Ok=
