language: c
dist: trusty
sudo: required
branches:
  only:
  - master
  - "/^issue.*/"
git:
  submodules: false
env:
  global:
  - BIN=fix-agda-whitespace
  matrix:
  - GHC_VER=8.6.5
  - GHC_VER=8.4.4
  - GHC_VER=8.2.2
  - GHC_VER=8.0.2
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo -E apt-add-repository -y "ppa:hvr/ghc"
- travis_apt_get_update
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install ghc-${GHC_VER}
- export PATH=/opt/ghc/$GHC_VER/bin:$PATH
- mkdir -p ~/.local/bin && export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
- export ARGS="--stack-yaml stack-${GHC_VER}.yaml --no-terminal --system-ghc"
- echo "*** GHC version ***"     && ghc     --version && echo "*** Stack version ***"   &&
  stack   --version
install:
- stack build ${ARGS} --only-dependencies
- stack build ${ARGS}
script:
- stack exec ${ARGS} -- ${BIN} --check
before_deploy:
- rm *.lock
- stack install ${ARGS} --local-bin-path .
- strip ${BIN}
- gzip ${BIN}
deploy:
  provider: releases
  skip_cleanup: true
  file: "${BIN}.gz"
  on:
    condition: $GHC_VER = 8.6.5
    tags: true
  api_key:
    secure: Opg82RES+K61MN1+aiOsM6Cp+DIhw6qm41y8qmHfsFGcCIJDDOIRY15G6yf9L0YisC9j2/Tha3QnRbNdxi4DZ3BO6eJ2gWBQN0he50FP9l7HHaYFoESgeLr1clnVAyT5eeHDmCaT2RYk5FFbJZ0dOPD/fC69FG4BvOVR+qDRDSSXMOO3bgdRbMnF/sVABNHd82oyqlXZuzc4PnUGiShVG/LNZHaGvDhFcWorfsMtK3fhLs+QTAjCFb/eHs1EfGyk+oOoaZylf5Ss/4lJ4jWRU7Lp75lZzLIivrZLdr7LIDzH8Mm8DHLs31aoEqA/Na7BH8UDJgxsGLzvWWcWQFDBpjLzRU7s6aN72IhmdVQRR9+y0infpmyt5rvC/CqwVXSGolG05tokrTjexTjMWmYYf0aJ7RNVijAq++55lG5Ye6YgYTdfY3YSrs3eQWRE2leLc56OyjeptK7Yng4bgZpAnmV7zXfsrP+VaOeAx/91iPqgu4xpmRWjvyCxdXxHoYqim7nOdu96Jyc/V82TrhHKKy2gzW8jICC3cmVuskL9y8BFO7tRdohC4do/IcU82L+q/GeWRLLhpd9aTWOiNQV1BYHfJN8rWprSW+9GUfihsAPspm/JMFc9rT/5pILUrLyYe6McJXf4d6kan5Izo25TieR4jpXjULa9ne/mDO/sYro=
